# Build off existing image, to cache extras
FROM s-fifteen/qkdserver:qkd-staging
COPY ./ /root/code/QKDServer
RUN \
    cd /root/code/QKDServer \
    && pip install -e .

# Use a temporary entrypoint to keep container running, for debugging
#ENTRYPOINT ["bash"]
